var data = ['disinfect doorknob',
'disinfect kitchen pulls',
'change a/c filter',
'wipe top of fridge',
'clean one fridge shelf',
'clean one fridge drawer',
'clean fridge coils',
'clean mirrors',
'wipe fridge door',
'pull 8 weeds',
'soak feet',
'meditate for 5 minutes',
'wipe computer screen',
'remove 7 items from your car',
'empty cutlery from dishwasher',
'sweep kitchen floor',
'put dirty clothes in laundry',
'clean 1 pot',
'collect used dishes from around home',
'eat one green vegetable',
'call a family member',
'write 3 lines of code',
'answer this question: what gave you joy and energy this week?',
'pour baking soda in your sink',
'spend no more than 10 minutes tweaking your resume',
'jot down 3 memorable points from articles you have read this week',
'shred 10 pieces of junk mail',
'practice 3 new keyboard shortcuts',
'breakdown 5 cardboard boxes',
'dust your liquor cabinet',
'lint roll yourself',
'put clothes in pile',
'papers into inbox',
'open 7 pieces of mail',
'put clothes in washer',
'choose 3 pieces to iron',
'take out recycling',
'clear off  dining room table'];